\i db/seeds/01_users.sql
\i db/seeds/02_quizzes.sql
\i db/seeds/03_trivia_questions.sql
\i db/seeds/04_trivia_answers.sql
\i db/seeds/05_trivia_results.sql
\i db/seeds/06_personality_outcomes.sql
\i db/seeds/07_personality_questions.sql
\i db/seeds/08_personality_results.sql
\i db/seeds/09_personality_answers.sql
\i db/seeds/10_ratings.sql
\i db/seeds/11_favourites.sql
\i db/seeds/12_real_quiz.sql
