-- Answers table seeds here
INSERT INTO answers (question_id, answer) VALUES (1, 'Answer 1');
INSERT INTO answers (question_id, answer) VALUES (1, 'Answer 2');
INSERT INTO answers (question_id, answer) VALUES (1, 'Answer 3');
INSERT INTO answers (question_id, answer, is_correct) VALUES (1, 'Answer 4', true);
INSERT INTO answers (question_id, answer) VALUES (2, 'Answer 1');
INSERT INTO answers (question_id, answer) VALUES (2, 'Answer 2');
INSERT INTO answers (question_id, answer) VALUES (2, 'Answer 3');
INSERT INTO answers (question_id, answer, is_correct) VALUES (2, 'Answer 4', true);
INSERT INTO answers (question_id, answer) VALUES (3, 'Answer 1');
INSERT INTO answers (question_id, answer) VALUES (3, 'Answer 2');
INSERT INTO answers (question_id, answer) VALUES (3, 'Answer 3');
INSERT INTO answers (question_id, answer, is_correct) VALUES (3, 'Answer 4', true);
INSERT INTO answers (question_id, answer) VALUES (4, 'Answer 1');
INSERT INTO answers (question_id, answer) VALUES (4, 'Answer 2');
INSERT INTO answers (question_id, answer) VALUES (4, 'Answer 3');
INSERT INTO answers (question_id, answer, is_correct) VALUES (4, 'Answer 4', true);
INSERT INTO answers (question_id, answer) VALUES (5, 'Answer 1');
INSERT INTO answers (question_id, answer) VALUES (5, 'Answer 2');
INSERT INTO answers (question_id, answer) VALUES (5, 'Answer 3');
INSERT INTO answers (question_id, answer, is_correct) VALUES (5, 'Answer 4', true);
INSERT INTO answers (question_id, answer) VALUES (6, 'Answer 1');
INSERT INTO answers (question_id, answer) VALUES (6, 'Answer 2');
INSERT INTO answers (question_id, answer) VALUES (6, 'Answer 3');
INSERT INTO answers (question_id, answer, is_correct) VALUES (6, 'Answer 4', true);
INSERT INTO answers (question_id, answer) VALUES (7, 'Answer 1');
INSERT INTO answers (question_id, answer) VALUES (7, 'Answer 2');
INSERT INTO answers (question_id, answer) VALUES (7, 'Answer 3');
INSERT INTO answers (question_id, answer, is_correct) VALUES (7, 'Answer 4', true);
INSERT INTO answers (question_id, answer) VALUES (8, 'Answer 1');
INSERT INTO answers (question_id, answer) VALUES (8, 'Answer 2');
INSERT INTO answers (question_id, answer) VALUES (8, 'Answer 3');
INSERT INTO answers (question_id, answer, is_correct) VALUES (8, 'Answer 4', true);
