INSERT INTO personality_outcomes (quiz_id,title,photo,description) VALUES (18,'Gryffindor', 'https://vignette.wikia.nocookie.net/harrypotter/images/b/b1/Gryffindor_ClearBG.png/revision/latest?cb=20190222162949', 'Gryffindor values courage, bravery, nerve, and chivalry!');
INSERT INTO personality_outcomes (quiz_id,title,photo,description) VALUES (18,'Stitch', 'https://i2.wp.com/www.4ye.co.uk/wp-content/uploads/2014/11/Stitch_by_cHaRiSmIc.jpg?resize=600%2C483', 'You got ____!');
INSERT INTO personality_outcomes (quiz_id,title,photo,description) VALUES (18,'Old Hag', 'https://d23.com/app/uploads/2016/10/780x463-101716_favorite-creepy-characters_1.jpg', 'You got ____!');
INSERT INTO personality_outcomes (quiz_id,title,photo,description) VALUES (19,'Hermione Granger', 'https://upload.wikimedia.org/wikipedia/en/d/d3/Hermione_Granger_poster.jpg', 'Hermione has a smart, serious exterior, as well as the intense drive to learn everything and solve all of the problems!');
INSERT INTO personality_outcomes (quiz_id,title,photo,description) VALUES (19,'Aladdin', 'https://s7d9.scene7.com/is/image/DisneyStoreES/Character_Assets_Atmb-sq_character-aladdin_launch?$sq-c$', 'You got ____!');
INSERT INTO personality_outcomes (quiz_id,title,photo,description) VALUES (19,'Mickey Mouse', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/hostedimages/1433905519i/15156249._SY540_.jpg', 'You got ____!');
INSERT INTO personality_outcomes (quiz_id,title,photo,description) VALUES (20,'Squirtle', 'https://cdn.bulbagarden.net/upload/thumb/3/39/007Squirtle.png/250px-007Squirtle.png', 'Squirtle is fierce and protective!');
INSERT INTO personality_outcomes (quiz_id,title,photo,description) VALUES (20,'Jasmine', 'https://upload.wikimedia.org/wikipedia/en/7/71/Princess_Jasmine_disney.png', 'You got ____!');
INSERT INTO personality_outcomes (quiz_id,title,photo,description) VALUES (20,'Donald Duck', 'https://d23.com/app/uploads/2015/07/010815_character-resolutions-feat-1.png', 'You got ____!');
