\i db/schema/01_users.sql
\i db/schema/02_quizzes.sql
\i db/schema/03_trivia_questions.sql
\i db/schema/04_trivia_answers.sql
\i db/schema/05_trivia_results.sql
\i db/schema/06_personality_outcomes.sql
\i db/schema/07_personality_questions.sql
\i db/schema/08_personality_results.sql
\i db/schema/09_personality_answers.sql
\i db/schema/10_ratings.sql
\i db/schema/11_favourites.sql
