\i db/schema/01_users.sql
\i db/schema/02_categories.sql
\i db/schema/03_quizzes.sql
\i db/schema/04_trivia_questions.sql
\i db/schema/05_trivia_answers.sql
\i db/schema/06_trivia_results.sql
\i db/schema/07_personality_outcomes.sql
\i db/schema/08_personality_questions.sql
\i db/schema/09_personality_answers.sql
\i db/schema/10_personality_results.sql
\i db/schema/11_ratings.sql
\i db/schema/12_favourites.sql
